### ISSUE TITLE
Install fails on higher versions of NodeJS

### ISSUE THREAD

**Issue by tawashley** [cartridge/cartridge-cli#15]
**Confirmation of this issue across multiple installs pending (stack trace taken from local install**
 
When on NodeJS version `6.x.x` install fail with the following message

```
/Users/tristanashley/Documents/cartridge/cartridge-cli/node_modules/got-zip/node_modules/got/node_modules/duplexify/index.js:161
  while ((data = this._readable2.read(state.buffer.length ? state.buffer[0].length : state.length)) !== null) {
                                                                           ^

TypeError: Cannot read property 'length' of undefined
    at Duplexify._forward (/Users/tristanashley/Documents/cartridge/cartridge-cli/node_modules/got-zip/node_modules/got/node_modules/duplexify/index.js:161:76)
    at IncomingMessage.onreadable (/Users/tristanashley/Documents/cartridge/cartridge-cli/node_modules/got-zip/node_modules/got/node_modules/duplexify/index.js:126:10)
    at emitNone (events.js:86:13)
    at IncomingMessage.emit (events.js:185:7)
    at emitReadable_ (_stream_readable.js:432:10)
    at emitReadable (_stream_readable.js:426:7)
    at readableAddChunk (_stream_readable.js:187:13)
    at IncomingMessage.Readable.push (_stream_readable.js:134:10)
    at HTTPParser.parserOnBody (_http_common.js:123:22)
    at TLSSocket.socketOnData (_http_client.js:363:20)
```

Using a lower version, such as 4.8.0, allows the the install to correctly finish.

Investigation for the issue - our code or 3rd party - and appropriate fix to improve cartridge-cli NodeJS version portability

**Comment by tawashley** [comment]
This issue is now resolved. There was an issue with my local `nvm` setup. Fresh clone of the repo solved it. Closing this issue.
